## TP1
### Simulación de tráfico Av. Gral. Paz

In [1]:
from lane import *

In [ ]:
test_simulation = Lane_simulation(900, 30, 13, 1, 0)
test_simulation.simulation()

In [3]:
acc = test_simulation.acc
spd = test_simulation.spd
pos = test_simulation.pos

Puntos en el mapa:
- Liniers: inicio del recorrido ([Ver en Google Maps](https://www.google.com.ar/maps/place/34%C2%B039'17.7%22S+58%C2%B031'38.4%22W/@-34.6549785,-58.5277805,17.81z/data=!4m4!3m3!8m2!3d-34.65491!4d-58.527343?entry=ttu))
- Acceso norte: cambio máxima de velocidad ([Ver en Google Maps](https://www.google.com.ar/maps/place/34%C2%B032'47.9%22S+58%C2%B029'34.2%22W/@-34.5463826,-58.4928312,20.08z/data=!4m4!3m3!8m2!3d-34.546634!4d-58.492842?entry=ttu))
- Lugones: fin del recorrido ([Ver en Google Maps](https://www.google.com.ar/maps/place/34%C2%B032'08.7%22S+58%C2%B028'05.8%22W/@-34.5357379,-58.4689167,19z/data=!3m1!4b1!4m4!3m3!8m2!3d-34.535739!4d-58.468273?entry=ttu))
- Distancia total 15.500 metros
- Distancia entre Liniers y Acceso Norte 13.000 metros

In [1]:
from road import *
simulation = RoadSimulation(30, 1, 4, 4, 2)

In [2]:
simulation.simulate()

a1
(1, 30)
(1, 30)


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 1 and the array at index 1 has size 30

In [3]:
acc_sim = simulation.acc
spd_sim = simulation.spd
pos_sim = simulation.pos

In [3]:
import numpy as np
np.random.seed(474)
test = np.random.randint(low=-9, high=10, size=(3,3))
test

array([[-9,  0,  6],
       [ 3, -1,  3],
       [ 4, -9,  2]])

In [4]:
new_row = np.zeros((1,test.shape[1]))

In [5]:
test = np.vstack((test, new_row))
test

array([[-9.,  0.,  6.],
       [ 3., -1.,  3.],
       [ 4., -9.,  2.],
       [ 0.,  0.,  0.]])

In [10]:
test[3,0] = 3
test

array([[-9.,  0.,  6.],
       [ 3., -1.,  3.],
       [ 4., -9.,  2.],
       [ 3.,  0.,  0.]])

In [11]:
new_row

array([[0., 0., 0.]])

In [6]:
i = 1
while i < len(test[:,1]):
    test[i,1] = 1
    i += 1

test

array([[-9.,  0.,  6.],
       [ 3.,  1.,  3.],
       [ 4.,  1.,  2.],
       [ 0.,  1.,  0.]])

In [3]:
spd = np.zeros((1,10))
new_agent = np.zeros((1,10))
spd = np.vstack((spd, new_agent))